FROM node:alpine AS build

ARG REACT_APP_CAPTCHA_PUBLIC
ARG CAPTCHA_SECRET
ARG DATABASE_URL_NEW
ARG FRONTEND_URL_NEW
ARG EMAIL_USER
ARG EMAIL_PASS
ARG JWT_SECRET
ARG CLOUDINARY_SECRET

ENV DATABASE_URL=$DATABASE_URL_NEW \
		EMAIL_USER=$EMAIL_USER \
		EMAIL_PASS=$EMAIL_PASS \
		REACT_APP_CAPTCHA_PUBLIC=$REACT_APP_CAPTCHA_PUBLIC \
		CAPTCHA_SECRET=$CAPTCHA_SECRET \
		REACT_APP_API_URL=/api \
    FRONTEND_URL_NEW=$FRONTEND_URL_NEW \
    JWT_SECRET=$JWT_SECRET \
    CLOUDINARY_SECRET=$CLOUDINARY_SECRET
    

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV NODE_ENV=production
RUN npm run build
CMD ["npm", "run", "production"]