FROM node:alpine AS build

ARG REACT_APP_API_URL
ARG DATABASE_URL
ARG FRONTEND_URL
ARG EMAIL_USER
ARG EMAIL_PASS

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV DATABASE_URL=$DATABASE_URL
ENV FRONTEND_URL=$FRONTEND_URL
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASS=$EMAIL_PASS

WORKDIR /app/
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
CMD ["npm", "run", "production"]